#!/bin/bash

LOG_DIR=/var/log/TGSBot
BOT_DIR=/var/opt/tgs/bot.tiga

BOT_DIR=/var/develop/TGSBot
LOG_DIR=${BOT_DIR}/log

start_bot() {
  cd $BOT_DIR
#  echo "./tgsBot.py -H ti-ga.com --port 4321 --user $1 -p $2 -s $3 > $LOG_DIR/$1.py.log 2>&1" | at now
  echo "./tgsBot.py -H localhost --port 8081 --user $1 -p $2 -s $3 -k 28000 > $LOG_DIR/$1.py.log 2>&1" | at now
}

start_bot $1 $2 $3
